import React from 'react';

// Static list of available packages (with Stripe product IDs)
const packages = [
  {
    id: 'prod_S4KGh5D8vVvBrh',
    name: 'Diet Plan Only',
    description: 'Get a personalized diet plan generated by AI.',
    price: '$9.99',
  },
  {
    id: 'prod_S4KMNgqdoGgcrD',
    name: 'Workout Plan Only',
    description: 'Access customized workouts based on your fitness goal.',
    price: '$12.99',
  },
  {
    id: 'prod_S4KPEjynXDYMKo',
    name: 'Full Coaching Bundle',
    description: 'Includes both diet + workouts + 1-month support.',
    price: '$19.99',
  },
];

const Packages = () => {
  // When user clicks "Buy Now", create a Stripe Checkout session
  const handlePurchase = async (priceId) => {
    const res = await fetch('http://localhost:5000/api/stripe/create-checkout-session', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ priceId }),
    });

    const data = await res.json();

    // Redirect user to Stripe checkout if session ID is returned
    if (data.id) {
      window.location.href = `https://checkout.stripe.com/pay/${data.id}`;
    }
  };

  return (
    <div style={{ maxWidth: '800px', margin: '40px auto', padding: '20px' }}>
      <h2>💼 Fitness Packages</h2>

      {/* Display each package as a card */}
      {packages.map((pkg) => (
        <div
          key={pkg.id}
          style={{
            border: '1px solid #ddd',
            padding: '20px',
            marginBottom: '20px',
            borderRadius: '10px',
            backgroundColor: '#f9f9f9',
          }}
        >
          <h3>{pkg.name}</h3>
          <p>{pkg.description}</p>
          <h4>{pkg.price}</h4>

          {/* Stripe Checkout button */}
          <button
            onClick={() => handlePurchase(pkg.id)}
            style={{
              backgroundColor: '#ff2625',
              color: 'white',
              padding: '10px 20px',
              border: 'none',
              borderRadius: '6px',
              cursor: 'pointer',
            }}
          >
            Buy Now
          </button>
        </div>
      ))}
    </div>
  );
};

export default Packages;
